### ISSUE TITLE
Howto for linux / users

### ISSUE THREAD

**Issue by ameeuw** [FZJ-IEK3-VSA/LoadProfileGenerator#1]
Hi, great work and great project.

I would really like to use the CLI under macOS or linux. 
I immediately got the Windows CLI version to work, but the simulation engine download for linux from the website https://www.loadprofilegenerator.de/download/ (10.3.0) is a mystery to me.
Is there an executable to use similar to the windows version?

Thank you for your efforts.

**Comment by noah80** [comment]
simengine2

You need to make it executable with chmod a+x simengine2. It's a bit annoying since I package in Windows and haven't figured out yet how to set the executable flag in a Windows-Zipfile. Sorry about that.

**Comment by ameeuw** [comment]
Nice, thank you for the quick reaction - that did the trick for me.

**Comment by brunorigal** [comment]
Hi, I have the same question. I did the chmod. However, once it is done, how can I run the software? Does it need Wine?
