### ISSUE TITLE
API for automated load profile generation

### ISSUE THREAD

**Issue by FruitVul** [FZJ-IEK3-VSA/LoadProfileGenerator#2]
I was wondering if the LoadProfileGenerator has an API. For example, it would be great if a python script could automate the load profile generation by reporting the specific parameters to the LPG.

If not it would increase the useability of the LPG by a lot!

**Comment by noah80** [comment]
There is a command line API that accepts json files. You can generate the json files with the api or with the python api. You can generate the python class structure from the command line.
Look here:
https://www.loadprofilegenerator.de/calculatinglargenumbers/

Also try out the simulationengine.exe and look at the options it gives you. One of them is for generating the python bindings.

**Comment by FruitVul** [comment]
Great news thank you!
