### ISSUE TITLE
Website not available (www.loadprofilegenerator.de)

### ISSUE THREAD

**Issue by hsteinacker-siz** [FZJ-IEK3-VSA/LoadProfileGenerator#36]
Hello,

we would like to have a look at the precompiled LoadProfileGenerator, but the website has been down for the last few days.
Is there any other way to get the compiled software? Or are you already working on a fix for the website?

Many thanks and best regards from southern Germany
Heiner

**Comment by mpauly-exnaton** [comment]
Hello Heiner, not affiliated with the project, but as far as I can tell you should be able to get binaries from the [Github release page](https://github.com/FZJ-IEK3-VSA/LoadProfileGenerator/releases/tag/v10.10.0).

**Comment by hsteinacker-siz** [comment]
Oh you're right, I could have thought of that myself - thank you very much!

**Comment by noah80** [comment]
Hi,

I finally got around to fixing the issue. The home page was victim of a botched linux update, and due to a high workload it took until today for me to get around to reinstalling everything...

Sorry about that.
Noah
